// Static descriptions shown by the 설명(View Details) popup on each module.
// 키워드: 역할(무엇을), 언제 사용, 입력(소비 데이터), 결과(산출물),
//        파라미터, 권장 연결(앞→뒤 모듈), 흔한 오류, 비고.
// 신규 JMDC 모듈(J1~J7)은 상세하게, 기존 모듈은 핵심 + 실용 가이드 위주로 작성.

import { ModuleType } from "./types";

export interface ModuleDescription {
  title: string;
  category?: string;
  role: string;
  input: string;
  output: string;
  parameters?: string;
  /** 언제 이 모듈을 쓰면 좋은지 — 사용 시점/판단 기준 */
  whenToUse?: string;
  /** 권장 연결 — 일반적인 업스트림(앞) → 다운스트림(뒤) 모듈 */
  connections?: string;
  /** 흔한 오류 — 자주 막히는 지점과 해결법 (경고 톤으로 표시) */
  commonErrors?: string;
  notes?: string;
}

export const MODULE_DESCRIPTIONS: Partial<
  Record<ModuleType, ModuleDescription>
> = {
  // ===== Data I/O =====
  [ModuleType.LoadData]: {
    title: "Load Data",
    category: "데이터 입출력",
    role: "CSV/Excel 파일을 업로드해 분석 파이프라인의 시작점으로 삼습니다. 파일은 브라우저에 업로드되어 Pyodide의 메모리에 DataFrame으로 로드됩니다.",
    input: "사용자가 선택한 로컬 .csv / .xlsx / .xls 파일. 헤더 행 1줄 + 데이터 행 N줄.",
    output: "전체 DataFrame. 후속 모듈(Statistics, SelectData, SplitData 등)에 그대로 연결합니다.",
    parameters: "fileContent: 파일 내용(브라우저가 자동 채움). source: 표시용 파일 경로.",
    whenToUse: "모든 파이프라인의 첫 모듈. 분석할 원본 데이터를 가져올 때 가장 먼저 배치합니다.",
    connections: "(시작점, 입력 없음) → Statistics · SelectData · HandleMissingValues · SplitData 등.",
    commonErrors: "파일 미실행 상태에서 하위 모듈을 돌리면 'LoadData를 먼저 실행' 오류. ▶로 먼저 실행하세요. 인코딩이 깨지면 UTF-8로 저장 후 재업로드.",
    notes: "파일 크기 20MB 이상이면 Pyodide 메모리 한계로 실행이 중단됩니다. 10MB 이상은 경고만 표시.",
  },
  [ModuleType.Statistics]: {
    title: "Statistics",
    category: "탐색적 분석",
    role: "수치형/범주형 컬럼별 기술통계(평균, 중앙값, 분산, 결측 비율), 상관행렬, 히트맵을 생성합니다.",
    input: "DataFrame 1개.",
    output: "기술통계표 + 상관계수 행렬 + 시각화. '결과 보기'로 모달에서 확인.",
    whenToUse: "분석 초반 데이터의 분포·결측·상관 구조를 한눈에 파악하고 싶을 때(EDA 첫 단계).",
    connections: "LoadData → Statistics. (분기 모듈 — 데이터를 변형하지 않으므로 결과 확인용으로 곁가지로 둡니다.)",
    commonErrors: "범주형이 많으면 상관행렬이 비어 보일 수 있습니다 — 수치형 컬럼이 2개 이상 필요.",
  },
  [ModuleType.SelectData]: {
    title: "Select Data",
    category: "데이터 가공",
    role: "분석에 사용할 컬럼만 골라내고, 각 컬럼의 역할(피처/타깃/시간)이나 자료형(수치/범주)을 지정합니다.",
    input: "DataFrame 1개.",
    output: "선택된 컬럼만 남은 DataFrame + 컬럼 메타데이터.",
    parameters: "columnSelections: {컬럼명: {selected, type, role}}",
    whenToUse: "불필요한 컬럼을 떼어내거나, 피처/타깃 역할을 명시해 후속 모델링을 단순화하고 싶을 때.",
    connections: "LoadData → SelectData → 전처리(HandleMissingValues/Encode) 또는 SplitData.",
    commonErrors: "타깃 컬럼을 실수로 제외하면 모델 모듈에서 라벨을 찾지 못합니다.",
  },
  [ModuleType.DataFiltering]: {
    title: "Data Filtering",
    category: "데이터 가공",
    role: "조건식(>, <, ==, in, between 등)으로 행을 부분 추출합니다. AND/OR 결합 가능.",
    input: "DataFrame 1개.",
    output: "필터 조건을 통과한 행만 남은 DataFrame.",
    whenToUse: "특정 기간·집단·값 범위로 분석 대상을 좁힐 때.",
    connections: "LoadData/SelectData → DataFiltering → 후속 분석/모델링.",
    commonErrors: "조건이 너무 엄격하면 0행이 남아 하위 모듈이 실패합니다 — 필터 후 행 수를 확인하세요. 문자열 비교는 정확한 값(대소문자 포함)이어야 합니다.",
  },
  [ModuleType.ColumnPlot]: {
    title: "Column Plot",
    category: "시각화",
    role: "단일 컬럼의 분포(히스토그램, KDE, 박스플롯)와 결측 패턴을 시각화합니다.",
    input: "DataFrame 1개 + 시각화할 컬럼명.",
    output: "PNG 이미지 + 컬럼 통계 요약.",
    whenToUse: "특정 변수의 분포 모양·치우침·이상치를 눈으로 확인하고 변환 필요성을 판단할 때.",
    connections: "어느 데이터 모듈 뒤든 곁가지로 연결. (변형하지 않는 확인용 모듈.)",
    commonErrors: "범주형 컬럼에 히스토그램을 적용하면 의미가 없을 수 있습니다 — 막대/빈도 플롯을 선택하세요.",
  },
  [ModuleType.OutlierDetector]: {
    title: "Outlier Detector",
    category: "데이터 품질",
    role: "IQR, Z-score, Isolation Forest 등으로 이상치를 탐지하고 표시/제거 옵션을 제공합니다.",
    input: "DataFrame 1개.",
    output: "이상치 플래그가 추가된 DataFrame + 이상치 통계 리포트.",
    parameters: "method: IQR / Z-score / Isolation Forest · threshold · 컬럼 선택",
    whenToUse: "모델 학습 전 극단값이 결과를 왜곡할 우려가 있을 때, 또는 데이터 품질을 점검할 때.",
    connections: "LoadData/SelectData → OutlierDetector → HandleMissingValues 또는 모델링.",
    commonErrors: "이상치를 무조건 제거하면 실제 신호(예: 고액 클레임)를 잃을 수 있습니다 — 도메인 판단 후 제거.",
  },
  [ModuleType.HypothesisTesting]: {
    title: "Hypothesis Testing",
    category: "통계 검정",
    role: "t-검정, ANOVA, χ², Mann-Whitney 등 가설검정을 수행해 p-value와 효과크기를 산출합니다.",
    input: "DataFrame 1개 + 검정 대상 컬럼.",
    output: "검정 결과 테이블(statistic, p-value, 결론).",
    parameters: "test: t-test / ANOVA / chi-square / Mann-Whitney · 그룹·대상 컬럼",
    whenToUse: "두 집단(또는 그 이상)의 차이가 우연인지 통계적으로 유의한지 판정할 때.",
    connections: "전처리된 DataFrame → HypothesisTesting. (결과 확인용 분기.)",
    commonErrors: "정규성·등분산 가정을 어기면 t/ANOVA 결과가 왜곡됩니다 — 먼저 NormalityChecker로 점검하고 비모수(Mann-Whitney)를 고려하세요.",
  },
  [ModuleType.NormalityChecker]: {
    title: "Normality Checker",
    category: "데이터 품질",
    role: "Shapiro-Wilk, K-S, Anderson-Darling 검정 + Q-Q plot으로 정규성을 평가합니다.",
    input: "DataFrame 1개 + 평가 대상 컬럼.",
    output: "검정 결과 + Q-Q plot + 권장 변환(log, sqrt 등).",
    whenToUse: "모수 검정(t/ANOVA)이나 선형회귀 가정을 확인하기 전, 변수의 정규성을 점검할 때.",
    connections: "수치형 DataFrame → NormalityChecker → (필요 시) TransformData → 검정/모델링.",
    commonErrors: "표본이 매우 크면 Shapiro-Wilk가 사소한 비정규도 '유의'로 판정합니다 — Q-Q plot을 함께 보세요.",
  },
  [ModuleType.Correlation]: {
    title: "Correlation",
    category: "탐색적 분석",
    role: "Pearson/Spearman/Kendall 상관계수 행렬과 히트맵을 생성합니다.",
    input: "DataFrame 1개.",
    output: "상관행렬 + p-value + 히트맵.",
    parameters: "method: pearson(선형) / spearman(순위) / kendall · cramers_v(범주형)",
    whenToUse: "변수 간 관계를 탐색하거나 다중공선성·중복 피처를 사전에 발견할 때.",
    connections: "수치형 DataFrame → Correlation. 강한 상관 발견 시 → VIFChecker로 다중공선성 정량화.",
    commonErrors: "상관은 인과가 아닙니다. 비선형 관계는 Pearson에서 0에 가깝게 나올 수 있어 Spearman과 비교하세요.",
  },
  [ModuleType.HandleMissingValues]: {
    title: "Handle Missing Values",
    category: "데이터 전처리",
    role: "결측치를 평균/중앙값/최빈값으로 대체하거나, KNN/회귀 보간, 또는 행 삭제를 적용합니다.",
    input: "DataFrame 1개.",
    output: "결측 처리된 DataFrame + 처리 로그.",
    parameters: "method: remove_row / impute(mean·median·mode) / knn",
    whenToUse: "모델·클러스터링·검정 대부분이 결측을 허용하지 않으므로, 모델링 전 거의 항상 거칩니다.",
    connections: "LoadData/SelectData → HandleMissingValues → EncodeCategorical/ScalingTransform → 모델링.",
    commonErrors: "결측을 처리하지 않고 모델/클러스터링을 돌리면 'null 값' 오류가 납니다. 행 삭제는 표본이 크게 줄 수 있으니 비율을 확인하세요.",
  },
  [ModuleType.EncodeCategorical]: {
    title: "Encode Categorical",
    category: "데이터 전처리",
    role: "범주형 변수를 One-Hot, Label, Ordinal, Target Encoding 등으로 수치화합니다.",
    input: "DataFrame 1개.",
    output: "인코딩된 DataFrame + 인코더 매핑 정보(추론 시 재사용).",
    parameters: "method: one_hot / label / ordinal / target · 대상 컬럼",
    whenToUse: "문자열 범주형을 수치만 받는 모델(회귀, 신경망, 거리 기반)에 넣기 전.",
    connections: "HandleMissingValues → EncodeCategorical → ScalingTransform → SplitData/모델링.",
    commonErrors: "고유값이 매우 많은 컬럼에 One-Hot을 쓰면 컬럼이 폭증합니다 — Target/Ordinal을 고려. 학습·추론에서 동일 매핑을 써야 합니다.",
  },
  [ModuleType.ScalingTransform]: {
    title: "Scaling Transform",
    category: "데이터 전처리",
    role: "수치형 변수를 MinMax / StandardScaler / RobustScaler로 변환합니다.",
    input: "DataFrame 1개.",
    output: "스케일링된 DataFrame + 스케일러 객체.",
    parameters: "method: MinMax(0~1) / StandardScaler(평균0,분산1) / RobustScaler(중앙값,IQR)",
    whenToUse: "거리/경사 기반 알고리즘(KMeans, KNN, SVM, 신경망, PCA) 전에는 거의 필수.",
    connections: "EncodeCategorical → ScalingTransform → KMeans/PCA/SVM/NeuralNetwork 등.",
    commonErrors: "트리 계열(DecisionTree, RandomForest)에는 효과가 없습니다. 이상치가 많으면 MinMax가 왜곡되니 RobustScaler를 고려.",
  },
  [ModuleType.TransformData]: {
    title: "Transform Data",
    category: "데이터 전처리",
    role: "로그/제곱근/Box-Cox/Yeo-Johnson 등 분포 변환을 적용합니다.",
    input: "DataFrame 1개 + 변환할 컬럼.",
    output: "변환된 DataFrame.",
    parameters: "transform: log / sqrt / box-cox / yeo-johnson · 대상 컬럼",
    whenToUse: "치우친(skewed) 분포를 정규에 가깝게 펴서 선형모델·검정 가정을 만족시키고 싶을 때.",
    connections: "NormalityChecker(진단) → TransformData → 검정/선형모델.",
    commonErrors: "log/Box-Cox는 0 이하 값에서 실패합니다 — 양수만 있거나 Yeo-Johnson을 사용하세요.",
  },
  [ModuleType.SplitData]: {
    title: "Split Data",
    category: "데이터 가공",
    role: "데이터를 학습/검증/테스트로 분할합니다. 무작위, 층화, 시간기반 모드 지원.",
    input: "DataFrame 1개 + 타깃 컬럼(층화 시).",
    output: "train_data_out, test_data_out 두 포트로 분리 출력.",
    parameters: "train_size · shuffle · stratify · stratify_column · random_state(기본 42, 재현성)",
    whenToUse: "지도학습에서 과적합을 막고 일반화 성능을 정직하게 평가하려 할 때.",
    connections: "전처리 완료 DataFrame → SplitData → (train_data_out)TrainModel · (test_data_out)ScoreModel/EvaluateModel.",
    commonErrors: "train·test 포트를 바꿔 연결하면 평가가 왜곡됩니다. 분류 불균형 시 stratify=True 권장. random_state를 비우면 매 실행 결과가 달라집니다(기본 42 유지 권장).",
  },
  [ModuleType.Concat]: {
    title: "Concat",
    category: "데이터 가공",
    role: "동일 스키마 DataFrame 2개를 행(axis=0) 또는 열(axis=1) 방향으로 결합합니다.",
    input: "DataFrame 2개 (data_in, data_in2).",
    output: "결합된 DataFrame.",
    parameters: "axis: 0(행 누적) / 1(열 붙이기)",
    whenToUse: "분할 저장된 같은 형식의 데이터를 합치거나(행), 별도로 만든 피처를 붙일 때(열).",
    connections: "두 데이터 소스 → Concat → 후속 분석/모델링.",
    commonErrors: "행 결합은 컬럼명이, 열 결합은 행 수가 일치해야 합니다. 두 번째 데이터 포트(data_in2) 연결을 빠뜨리기 쉽습니다.",
  },
  [ModuleType.Join]: {
    title: "Join",
    category: "데이터 가공",
    role: "키 컬럼을 기준으로 두 DataFrame을 inner/left/right/outer 조인합니다.",
    input: "DataFrame 2개 (data_in, data_in2) + join key.",
    output: "조인된 DataFrame.",
    parameters: "how: inner / left / right / outer · on(키 컬럼)",
    whenToUse: "공통 키(회원ID 등)로 서로 다른 테이블의 정보를 한 행에 합칠 때.",
    connections: "두 데이터 소스 → Join → 후속 분석/모델링.",
    commonErrors: "키 컬럼명이 양쪽에서 다르거나 자료형이 다르면 매칭 실패. inner 조인은 매칭 안 된 행이 사라지니 결과 행 수를 확인하세요.",
  },
  [ModuleType.TransitionData]: {
    title: "Transition Data",
    category: "데이터 가공",
    role: "장형(long) ↔ 광형(wide) 변환(pivot/melt)을 수행합니다.",
    input: "DataFrame 1개.",
    output: "재구조화된 DataFrame.",
    whenToUse: "시계열을 연도×지표 표로 펼치거나(wide), 모델 입력용으로 다시 녹일(long) 때.",
    connections: "LoadData → TransitionData → 사망률 모델(연령×연도 행렬) 등.",
    commonErrors: "pivot 시 인덱스+컬럼 조합이 중복되면 집계 함수가 필요합니다.",
  },
  [ModuleType.ResampleData]: {
    title: "Resample Data",
    category: "데이터 가공",
    role: "시계열 데이터를 일/주/월 단위로 리샘플링하거나 클래스 불균형을 SMOTE/언더샘플링으로 보정합니다.",
    input: "DataFrame 1개.",
    output: "리샘플링된 DataFrame.",
    parameters: "mode: 시간 리샘플(freq) / 클래스 균형(SMOTE·under·over)",
    whenToUse: "희귀 클래스 비율을 높여 분류 성능을 개선하거나, 시계열 주기를 통일할 때.",
    connections: "SplitData(train만) → ResampleData → 모델링. (불균형 보정은 train에만 적용.)",
    commonErrors: "SMOTE를 test에도 적용하면 성능이 부풀려집니다 — 학습 데이터에만 쓰세요. SMOTE는 수치형 피처를 요구합니다.",
  },

  // ===== Supervised Learning =====
  [ModuleType.LinearRegression]: {
    title: "Linear Regression",
    category: "지도학습 (회귀)",
    role: "연속형 타깃을 선형 결합으로 예측합니다. 해석성 우선 시 첫 베이스라인.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel에서 X_train·y_train으로 수행.",
    output: "학습되지 않은 모델 객체(model). TrainModel로 연결.",
    parameters: "model_type: LinearRegression/Lasso/Ridge/ElasticNet · fit_intercept · alpha · l1_ratio",
    whenToUse: "타깃이 연속형이고 해석 가능한 베이스라인이 필요할 때. 정규화(Lasso/Ridge)로 과적합 억제.",
    connections: "(model_in)→ TrainModel ←(data_in)SplitData.train → ScoreModel → EvaluateModel.",
    commonErrors: "이 모듈만으로는 학습되지 않습니다 — 반드시 TrainModel에 연결하세요. 강한 다중공선성은 계수를 불안정하게 합니다(Ridge 권장).",
  },
  [ModuleType.LogisticRegression]: {
    title: "Logistic Regression",
    category: "지도학습 (분류)",
    role: "이진/다항 분류기. log-odds 해석 가능, 정규화(L1/L2) 지원.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 분류 모델(model).",
    whenToUse: "분류의 해석 가능한 베이스라인이 필요하거나, 변수 영향(odds)을 보고 싶을 때.",
    connections: "→ TrainModel → ScoreModel → EvaluateModel(분류 지표).",
    commonErrors: "라벨이 연속형이면 분류가 되지 않습니다. 클래스 불균형 시 지표 해석에 주의(AUC·F1 병행).",
  },
  [ModuleType.PoissonRegression]: {
    title: "Poisson Regression",
    category: "지도학습 (카운트)",
    role: "건수 데이터(클레임 횟수, 사건 수) 예측. 평균=분산 가정.",
    input: "(모델 정의) 하이퍼파라미터만 + (학습 시) X_train, y_train(count) + exposure(option).",
    output: "학습되지 않은 GLM 모델.",
    whenToUse: "타깃이 음이 아닌 정수(횟수)이고 노출량(exposure)을 반영하고 싶을 때.",
    connections: "→ TrainModel → ScoreModel/EvaluateModel. 과대분산이면 NegativeBinomial로 교체.",
    commonErrors: "분산이 평균보다 크게 크면(과대분산) 표준오차가 과소추정됩니다 — NB를 고려하세요.",
  },
  [ModuleType.NegativeBinomialRegression]: {
    title: "Negative Binomial Regression",
    category: "지도학습 (카운트)",
    role: "과대분산 카운트 데이터에 사용. Poisson보다 분산 모수가 자유로움.",
    input: "(모델 정의) 하이퍼파라미터만 + (학습 시) X_train, y_train(count).",
    output: "학습되지 않은 NB GLM 모델.",
    whenToUse: "카운트 타깃의 분산이 평균보다 뚜렷이 클 때(과대분산).",
    connections: "→ TrainModel → ScoreModel/EvaluateModel.",
    commonErrors: "과대분산이 없으면 Poisson이 더 단순·안정적입니다.",
  },
  [ModuleType.DecisionTree]: {
    title: "Decision Tree",
    category: "지도학습",
    role: "단일 의사결정 트리. 시각화/해석성 강점, 단일 트리는 과적합 경향.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 트리 모델(model).",
    parameters: "model_purpose(classification/regression) · criterion · max_depth · min_samples_split/leaf · class_weight",
    whenToUse: "규칙 기반의 해석 가능한 모델이 필요하거나, 앙상블(RF)의 베이스라인으로.",
    connections: "→ TrainModel → ScoreModel → EvaluateModel.",
    commonErrors: "max_depth를 제한하지 않으면 쉽게 과적합합니다 — 깊이/리프 최소 표본을 설정하세요.",
  },
  [ModuleType.RandomForest]: {
    title: "Random Forest",
    category: "지도학습 (앙상블)",
    role: "다수 트리의 평균/투표. 강건한 일반화 + feature importance.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 RF 모델 + (학습 후) 변수중요도.",
    whenToUse: "표 형식 데이터에서 튜닝 없이 좋은 성능이 필요한 기본 선택지.",
    connections: "→ TrainModel → ScoreModel → EvaluateModel. 중요도 확인은 ResultModel.",
    commonErrors: "트리가 많으면 학습이 느려집니다(Pyodide). feature importance는 상관 피처 간 분산될 수 있습니다.",
  },
  [ModuleType.GradientBoosting]: {
    title: "Gradient Boosting",
    category: "지도학습 (앙상블)",
    role: "약한 트리를 순차적으로 부스팅. 표 형식 데이터에서 강력한 예측 성능.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 GBM 모델 + (학습 후) 변수중요도.",
    parameters: "model_purpose(classification/regression) · n_estimators(기본 100) · learning_rate(기본 0.1) · max_depth(기본 3) · random_state=42(고정)",
    whenToUse: "책 Ch3의 Boosted Decision Tree처럼 정확도가 중요한 분류·회귀에. RandomForest보다 종종 더 높은 성능.",
    connections: "→ TrainModel → ScoreModel → EvaluateModel. 중요도 확인은 ResultModel.",
    commonErrors: "learning_rate가 크면 과적합·불안정. n_estimators가 많으면 학습이 느려집니다(Pyodide). 부스팅은 순차적이라 RF보다 느릴 수 있습니다.",
  },
  [ModuleType.NeuralNetwork]: {
    title: "Neural Network",
    category: "지도학습",
    role: "다층 퍼셉트론(MLP). 비선형/복잡 패턴 학습.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 NN 모델(model).",
    parameters: "model_purpose · hidden_layer_sizes(예: '100,50') · activation · max_iter · random_state(기본 42)",
    whenToUse: "비선형 관계가 강하고 표본이 충분할 때. 스케일링이 사실상 필수.",
    connections: "ScalingTransform → SplitData → TrainModel(+NN) → ScoreModel → EvaluateModel.",
    commonErrors: "스케일링 없이 쓰면 수렴이 느리거나 실패합니다. max_iter가 작으면 미수렴 경고가 납니다.",
  },
  [ModuleType.SVM]: {
    title: "Support Vector Machine",
    category: "지도학습",
    role: "마진 최대화 기반 분류/회귀. 커널로 비선형 확장.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 SVM 모델(model).",
    whenToUse: "표본이 크지 않고 경계가 복잡할 때(커널). 스케일링 필수.",
    connections: "ScalingTransform → SplitData → TrainModel(+SVM) → ScoreModel → EvaluateModel.",
    commonErrors: "대용량에서 매우 느립니다. 스케일링을 빠뜨리면 성능이 급락합니다.",
  },
  [ModuleType.LDA]: {
    title: "Linear Discriminant Analysis",
    category: "지도학습 (분류)",
    role: "클래스별 공분산이 같다는 가정 하에 선형 결정경계 학습 + 차원축소.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 LDA 모델 + (학습 후) 변환 행렬.",
    whenToUse: "분류 + 시각화용 저차원 투영을 동시에 원할 때.",
    connections: "→ TrainModel → ScoreModel → EvaluateModel.",
    commonErrors: "클래스별 공분산이 크게 다르면 가정이 깨집니다(QDA 고려). 피처 수>표본이면 불안정.",
  },
  [ModuleType.NaiveBayes]: {
    title: "Naive Bayes",
    category: "지도학습 (분류)",
    role: "독립 가정 기반 베이즈 분류. 텍스트/희소 데이터에 강함.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainModel.",
    output: "학습되지 않은 NB 모델(model).",
    whenToUse: "빠른 베이스라인이 필요하거나 고차원 희소 피처(텍스트 빈도)일 때.",
    connections: "→ TrainModel → ScoreModel → EvaluateModel.",
    commonErrors: "강한 피처 상관이 있으면 독립 가정 위반으로 확률 보정이 나빠집니다.",
  },
  [ModuleType.KNN]: {
    title: "K-Nearest Neighbors",
    category: "지도학습",
    role: "가까운 K개 이웃의 다수결/평균으로 예측. 학습 없음, 추론 비용 높음.",
    input: "(모델 정의) 하이퍼파라미터만 + (추론 시) 학습 데이터 보유.",
    output: "학습 데이터를 보유한 KNN 모델.",
    parameters: "n_neighbors(K) · weights · 거리 척도",
    whenToUse: "경계가 비선형이고 표본이 작을 때의 간단한 비모수 베이스라인.",
    connections: "ScalingTransform → SplitData → TrainModel(+KNN) → ScoreModel → EvaluateModel.",
    commonErrors: "스케일링이 없으면 단위 큰 변수가 거리를 지배합니다. 표본이 크면 추론이 느립니다.",
  },

  // ===== Model Operations =====
  [ModuleType.TrainModel]: {
    title: "Train Model",
    category: "모델 연산",
    role: "모델 정의 모듈(model)과 학습 데이터를 받아 model.fit(X, y)를 실행합니다.",
    input: "model_in: 모델 객체 + data_in: X_train·y_train (SplitData.train).",
    output: "학습된 모델(trained_model).",
    parameters: "feature_columns · label_column",
    whenToUse: "지도학습 모델 정의(LinearRegression/DecisionTree 등)를 실제로 적합시킬 때.",
    connections: "(model_in)모델정의 · (data_in)SplitData.train → TrainModel → ScoreModel/EvaluateModel.",
    commonErrors: "model_in·data_in 둘 다 연결해야 합니다. label_column 미지정 시 학습 실패. 피처에 결측·문자열이 남아 있으면 fit 오류.",
  },
  [ModuleType.SweepParameters]: {
    title: "Sweep Parameters",
    category: "모델 연산",
    role: "모델 정의와 학습 데이터를 받아 GridSearchCV(기본·완전 결정적)로 하이퍼파라미터를 탐색하고, 최적 적합 추정기를 출력합니다(TrainModel 출력과 동일하게 Score/Evaluate로 연결).",
    input: "model_in: 미적합 모델 객체 + data_in: X_train·y_train (SplitData.train).",
    output: "최적 적합 모델(trained_model = best_estimator_) + best_params_ · best_score_.",
    parameters: "feature_columns · label_column · search_strategy(GridSearchCV/RandomizedSearchCV) · param_grid(JSON) · cv(정수) · scoring · n_iter",
    whenToUse: "단일 파라미터 학습 대신 교차검증으로 하이퍼파라미터를 자동 튜닝할 때.",
    connections: "(model_in)모델정의 · (data_in)SplitData.train → SweepParameters → ScoreModel/EvaluateModel.",
    commonErrors: "model_in·data_in 둘 다 연결해야 합니다. param_grid는 추정기 파라미터명 키를 가진 JSON이어야 합니다. cv는 2 이상 정수(결정성 보장). RandomizedSearchCV는 random_state=42로 고정됩니다.",
  },
  [ModuleType.ScoreModel]: {
    title: "Score Model",
    category: "모델 연산",
    role: "학습된 모델로 새 데이터의 예측값/확률을 계산합니다.",
    input: "학습된 모델(trained_model) + X_test (또는 신규 데이터).",
    output: "예측 결과 DataFrame (원본 + Predict 컬럼).",
    whenToUse: "학습된 모델로 테스트셋/실데이터를 예측해 결과를 산출할 때.",
    connections: "TrainModel → ScoreModel ←(data) SplitData.test → EvaluateModel.",
    commonErrors: "학습에 쓰인 피처 컬럼과 추론 데이터의 컬럼이 일치해야 합니다. 인코딩/스케일링 기준도 동일해야 합니다.",
  },
  [ModuleType.EvaluateModel]: {
    title: "Evaluate Model",
    category: "모델 연산",
    role: "분류는 Accuracy/Precision/Recall/F1/AUC, 회귀는 MSE/RMSE/MAE/R² 등을 산출합니다.",
    input: "예측 결과(scored_data) + 실제값(label).",
    output: "지표 표 + 혼동행렬 / 잔차 plot.",
    parameters: "model_type(classification/regression) · label_column · prediction_column",
    whenToUse: "모델 성능을 정량 지표로 확인하고 모델 간 비교를 할 때.",
    connections: "ScoreModel → EvaluateModel. 또는 TrainModel→(model_in) + SplitData.test→(data_in).",
    commonErrors: "model_type(분류/회귀)을 실제 타깃과 맞춰야 지표가 맞습니다. 라벨/예측 컬럼명을 정확히 지정하세요.",
  },

  // ===== Unsupervised: Clustering / Dimensionality Reduction =====
  [ModuleType.KMeans]: {
    title: "K-Means Clustering",
    category: "비지도학습",
    role: "K개 중심으로 데이터를 군집화합니다. 구형(등방) 클러스터에 적합.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainClusteringModel.",
    output: "학습되지 않은 KMeans 추정기(model).",
    parameters: "n_clusters(3) · init(k-means++) · n_init(10) · max_iter(300) · random_state(42)",
    whenToUse: "군집 개수를 대략 알고 있고, 크기가 비슷한 둥근 군집을 빠르게 나누고 싶을 때.",
    connections: "(model_in)KMeans · (data_in)데이터 → TrainClusteringModel → ClusteringData(cluster 라벨).",
    commonErrors: "스케일링을 빠뜨리면 단위 큰 변수가 거리를 지배합니다. K는 Elbow/Silhouette로 선택. 비구형/밀도 군집엔 DBSCAN을 쓰세요.",
  },
  [ModuleType.PCA]: {
    title: "Principal Component Analysis",
    category: "비지도학습 (차원축소)",
    role: "분산이 최대인 직교 방향(주성분)으로 데이터를 변환합니다. 시각화/잡음 제거/특성 추출.",
    input: "(모델 정의) 하이퍼파라미터만. 적합은 TrainClusteringModel.",
    output: "학습되지 않은 PCA 추정기(model).",
    parameters: "n_components(2)",
    whenToUse: "고차원 데이터를 2~3차원으로 시각화하거나, 상관된 피처를 압축할 때.",
    connections: "ScalingTransform → (model_in)PCA → TrainClusteringModel → ClusteringData(PC1, PC2…).",
    commonErrors: "스케일링이 없으면 분산 큰 변수에 주성분이 쏠립니다. 주성분은 해석이 어려울 수 있습니다.",
  },
  [ModuleType.DBSCAN]: {
    title: "DBSCAN Clustering",
    category: "비지도학습",
    role: "밀도 기반 군집화. 임의 모양의 군집을 찾고 밀도가 낮은 점은 노이즈(-1)로 표시합니다. 군집 수를 미리 정하지 않습니다.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainClusteringModel.",
    output: "학습되지 않은 DBSCAN 추정기(model). 적합 시 각 점에 cluster 라벨(-1=노이즈) 부여.",
    parameters: "eps(이웃 반경, 0.5) · min_samples(핵심점 최소 이웃 수, 5)",
    whenToUse: "군집 개수를 모르거나, 비구형 군집·이상치 검출이 필요할 때. KMeans가 잘 안 되는 경우의 대안.",
    connections: "ScalingTransform → (model_in)DBSCAN · (data_in)데이터 → TrainClusteringModel → ClusteringData.",
    commonErrors: "eps가 너무 작으면 대부분 노이즈(-1), 크면 한 덩어리가 됩니다 — 스케일링 후 조정하세요. transductive라 새 데이터 예측 불가: ClusteringData에는 학습과 동일한 데이터를 연결해야 합니다.",
    notes: "transductive 알고리즘 — .predict가 없어 .fit으로 계산한 labels_를 그대로 사용합니다.",
  },
  [ModuleType.HierarchicalClustering]: {
    title: "Hierarchical Clustering",
    category: "비지도학습",
    role: "점들을 아래에서 위로 병합(Agglomerative)해 군집 트리를 만든 뒤, 지정한 군집 수로 자릅니다.",
    input: "(모델 정의) 하이퍼파라미터만. 학습은 TrainClusteringModel.",
    output: "학습되지 않은 AgglomerativeClustering 추정기(model). 적합 시 cluster 라벨 부여.",
    parameters: "n_clusters(3) · linkage(ward/complete/average/single) · metric(euclidean; ward는 euclidean 강제)",
    whenToUse: "군집 간 계층 구조를 보고 싶거나, 군집 수를 사후에 조정하며 탐색할 때.",
    connections: "ScalingTransform → (model_in)Hierarchical · (data_in)데이터 → TrainClusteringModel → ClusteringData.",
    commonErrors: "transductive라 새 데이터 예측 불가: ClusteringData에 학습과 동일한 데이터를 연결하세요. 표본이 크면 메모리·시간이 급증합니다.",
    notes: "transductive 알고리즘 — .labels_를 그대로 사용. ward linkage는 euclidean metric만 지원합니다.",
  },
  [ModuleType.TrainClusteringModel]: {
    title: "Train Clustering Model",
    category: "비지도학습",
    role: "클러스터링/차원축소 모델 정의(KMeans/PCA/DBSCAN/Hierarchical)를 데이터에 적합(fit)시킵니다.",
    input: "model_in: 추정기 정의 + data_in: DataFrame(수치형).",
    output: "학습된(적합된) 모델. ClusteringData로 연결.",
    parameters: "feature_columns(비우면 모든 수치형 컬럼 자동 사용)",
    whenToUse: "비지도 추정기를 실제 데이터에 학습시킬 때(지도학습의 TrainModel에 해당).",
    connections: "(model_in)KMeans/PCA/DBSCAN/Hierarchical · (data_in)전처리 데이터 → TrainClusteringModel → ClusteringData.",
    commonErrors: "model_in·data_in 둘 다 연결 필수. 수치형 컬럼이 없으면 실패 — 인코딩/스케일링을 먼저 적용하세요.",
  },
  [ModuleType.ClusteringData]: {
    title: "Clustering Data",
    category: "비지도학습",
    role: "학습된 모델로 데이터에 결과를 부여합니다. 군집(KMeans)은 cluster 라벨, PCA는 주성분(PC1,PC2…), 밀도/계층(DBSCAN/Hierarchical)은 fit 시점 라벨.",
    input: "model_in: 학습된 모델 + data_in: DataFrame.",
    output: "cluster 라벨 또는 주성분 컬럼이 추가된 DataFrame.",
    whenToUse: "학습된 클러스터링/PCA 결과를 실제 데이터에 적용해 산출물을 만들 때.",
    connections: "TrainClusteringModel → ClusteringData ←(data_in)데이터 → (시각화/후속 분석).",
    commonErrors: "DBSCAN·Hierarchical(transductive)은 새 데이터를 예측할 수 없어, 학습에 쓴 동일 데이터를 data_in에 연결해야 합니다(행 수 불일치 시 오류). KMeans/PCA는 새 데이터도 가능.",
  },

  // ===== Stat Models (Traditional) =====
  [ModuleType.StatModels]: {
    title: "Stat Models",
    category: "전통 통계 모델",
    role: "OLS/Logit/Poisson/NB/Gamma/Tweedie GLM을 statsmodels로 적합. 계수 신뢰구간/p-value 산출.",
    input: "X_train, y_train.",
    output: "적합된 모델 + 계수표.",
    parameters: "model: OLS / Logit / Poisson / NegativeBinomial / Gamma / Tweedie",
    whenToUse: "예측보다 계수의 유의성·신뢰구간 등 통계적 추론이 중요할 때.",
    connections: "전처리 데이터 → StatModels → ResultModel/EvaluateStat.",
    commonErrors: "model 종류를 타깃 분포와 맞춰야 합니다(카운트→Poisson/NB, 이진→Logit).",
  },
  [ModuleType.OLSModel]: {
    title: "OLS Model",
    category: "전통 통계 모델",
    role: "최소제곱 선형회귀. 계수, t-stat, p-value, R² 산출.",
    input: "(모델 정의) DataFrame + 종속·독립 변수 지정.",
    output: "정의 객체. 실제 적합 결과는 ResultModel이 생성.",
    whenToUse: "연속형 타깃의 선형 관계와 각 변수의 유의성을 해석할 때.",
    connections: "(model_in)OLSModel → ResultModel(적합·계수표). 다중공선성은 VIFChecker로 점검.",
    commonErrors: "이 모듈은 정의만 합니다 — 적합 결과는 ResultModel에 연결해야 나옵니다. 잔차 정규성·등분산 가정을 확인하세요.",
  },
  [ModuleType.LogisticModel]: {
    title: "Logistic Model",
    category: "전통 통계 모델",
    role: "이진 로지스틱 GLM. odds ratio, Wald p-value 산출.",
    input: "(모델 정의) DataFrame + 이진 종속 변수.",
    output: "정의 객체. 적합 결과는 ResultModel.",
    whenToUse: "이진 결과(발생/비발생)에 대한 변수별 오즈비를 해석할 때.",
    connections: "(model_in)LogisticModel → ResultModel(오즈비·p-value).",
    commonErrors: "완전분리(perfect separation)가 있으면 계수가 발산합니다. 종속변수는 0/1 이진이어야 합니다.",
  },
  [ModuleType.PoissonModel]: {
    title: "Poisson Model",
    category: "전통 통계 모델",
    role: "Poisson GLM. 카운트 데이터 + offset(노출량) 지원.",
    input: "(모델 정의) DataFrame + count 종속 변수 (+ offset).",
    output: "정의 객체. 적합 결과는 ResultModel.",
    whenToUse: "발생 건수를 노출량 대비로 모델링할 때(발생률).",
    connections: "(model_in)PoissonModel → ResultModel. 과대분산이면 NegativeBinomialModel.",
    commonErrors: "과대분산을 무시하면 p-value가 과소추정됩니다 — EvaluateStat의 deviance로 점검.",
  },
  [ModuleType.QuasiPoissonModel]: {
    title: "Quasi-Poisson Model",
    category: "전통 통계 모델",
    role: "과대분산 보정 Poisson. 분산이 평균의 상수배라고 가정.",
    input: "(모델 정의) DataFrame + count 종속.",
    output: "정의 객체. 적합 결과는 ResultModel.",
    whenToUse: "경미~중간 과대분산을 표준오차 보정으로 다루고 싶을 때.",
    connections: "(model_in)QuasiPoissonModel → ResultModel.",
    commonErrors: "강한 과대분산은 NegativeBinomial이 더 적절합니다.",
  },
  [ModuleType.NegativeBinomialModel]: {
    title: "Negative Binomial Model",
    category: "전통 통계 모델",
    role: "NB GLM. 과대분산 카운트에 적합 (α 자유 추정).",
    input: "(모델 정의) DataFrame + count 종속.",
    output: "정의 객체. 적합 결과는 ResultModel.",
    whenToUse: "카운트 타깃의 분산이 평균보다 뚜렷이 클 때.",
    connections: "(model_in)NegativeBinomialModel → ResultModel.",
    commonErrors: "과대분산이 없으면 Poisson이 더 단순합니다. α 추정이 불안정하면 표본/공변량을 점검하세요.",
  },
  [ModuleType.DiversionChecker]: {
    title: "Diversion Checker",
    category: "데이터 품질",
    role: "두 데이터셋의 분포 차이(KS, PSI, Wasserstein 등)를 비교해 drift를 진단합니다.",
    input: "DataFrame 2개 (예: train vs prod).",
    output: "컬럼별 drift 점수 + 위험 등급.",
    whenToUse: "학습 데이터와 운영 데이터의 분포가 달라졌는지(데이터 드리프트) 점검할 때.",
    connections: "두 데이터 소스 → DiversionChecker.",
    commonErrors: "두 데이터의 컬럼 구성이 동일해야 비교됩니다.",
  },
  [ModuleType.EvaluateStat]: {
    title: "Evaluate Stat",
    category: "모델 연산",
    role: "전통 통계 모델의 적합도(AIC, BIC, deviance, pseudo-R²) 및 잔차 진단을 수행합니다.",
    input: "적합된 statsmodels 결과.",
    output: "적합도 지표 + 잔차 plot.",
    whenToUse: "GLM/회귀의 적합도를 비교하거나 가정 위반(잔차 패턴)을 진단할 때.",
    connections: "StatModels/ResultModel → EvaluateStat.",
    commonErrors: "AIC/BIC는 동일 데이터에 적합한 모델끼리만 비교 가능합니다.",
  },
  [ModuleType.VIFChecker]: {
    title: "VIF Checker",
    category: "데이터 품질",
    role: "Variance Inflation Factor로 다중공선성을 진단합니다. 통상 VIF>10이면 위험.",
    input: "DataFrame (수치형).",
    output: "변수별 VIF 표.",
    whenToUse: "회귀 전 독립변수 간 중복(다중공선성)으로 계수가 불안정해질지 점검할 때.",
    connections: "Correlation(탐색) → VIFChecker → 변수 제거/Ridge.",
    commonErrors: "범주형은 인코딩 후 평가하세요. VIF가 높은 변수를 한 번에 다 빼지 말고 하나씩 재평가합니다.",
  },

  // ===== Result / Predict =====
  [ModuleType.ResultModel]: {
    title: "Result Model",
    category: "출력",
    role: "통계 모델 정의(OLS/Logit 등)를 받아 실제 적합을 수행하고, 계수표·진단을 종합 출력합니다.",
    input: "model_in: 통계 모델 정의 + 데이터.",
    output: "적합 결과(계수·p-value·적합도) 통합 뷰.",
    whenToUse: "OLSModel 등 statsmodels 정의 모듈의 적합 결과를 실제로 산출할 때.",
    connections: "OLSModel/LogisticModel/… → ResultModel → EvaluateStat.",
    commonErrors: "연결된 모델 정의 종류에 따라 코드가 달라집니다 — 정의 모듈을 model_in에 연결해야 합니다.",
  },
  [ModuleType.PredictModel]: {
    title: "Predict Model",
    category: "모델 연산",
    role: "학습된 모델 + 신규 데이터로 예측 + 위험 카테고리 분류.",
    input: "학습된 모델 + 신규 X.",
    output: "예측값 + 위험 등급.",
    whenToUse: "학습된 모델을 새 데이터에 적용해 예측·위험 분류를 산출할 때.",
    connections: "TrainModel → PredictModel ←(신규 데이터).",
    commonErrors: "신규 데이터의 피처/전처리가 학습 시와 동일해야 합니다.",
  },

  // ===== Mortality =====
  [ModuleType.MortalityResult]: {
    title: "Mortality Result",
    category: "사망률 모델",
    role: "사망률 모델 적합 결과를 표·그래프로 종합합니다.",
    input: "사망률 모델 객체.",
    output: "예측 사망률 + life table.",
    whenToUse: "Lee-Carter/CBD 등 사망률 모델의 적합·예측 결과를 종합 확인할 때.",
    connections: "LeeCarter/CBD/APC/RH/Plat/PSpline → MortalityResult.",
    commonErrors: "입력 사망률 행렬(연령×연도)의 결측·0 값이 모델 적합을 방해할 수 있습니다.",
  },
  [ModuleType.LeeCarterModel]: {
    title: "Lee-Carter Model",
    category: "사망률 모델",
    role: "Lee-Carter 분해(age ax + period kt × bx)로 로그 사망률을 모델링.",
    input: "연령×연도 사망률 행렬.",
    output: "ax, bx, kt 추정치 + 예측.",
    whenToUse: "장기 사망률 추세를 모델링·예측하는 표준 베이스라인이 필요할 때.",
    connections: "TransitionData(행렬화) → LeeCarterModel → MortalityResult.",
    commonErrors: "연도가 너무 짧으면 kt 추세 추정이 불안정합니다.",
  },
  [ModuleType.CBDModel]: {
    title: "CBD Model",
    category: "사망률 모델",
    role: "Cairns-Blake-Dowd 2-factor 모델. 고령층 사망률에 강점.",
    input: "logit 변환 사망률.",
    output: "두 시계열 요인 + 예측.",
    whenToUse: "고연령(연금·생명) 사망률을 모델링할 때.",
    connections: "TransitionData → CBDModel → MortalityResult.",
    commonErrors: "저연령 구간에는 적합이 떨어질 수 있습니다.",
  },
  [ModuleType.APCModel]: {
    title: "APC Model",
    category: "사망률 모델",
    role: "Age-Period-Cohort 모델. 코호트 효과 분리.",
    input: "연령×연도 사망률.",
    output: "APC 분해 + 예측.",
    whenToUse: "출생 코호트 효과를 분리해 보고 싶을 때.",
    connections: "TransitionData → APCModel → MortalityResult.",
    commonErrors: "APC는 식별(identification) 문제가 있어 제약 가정에 따라 해석이 달라집니다.",
  },
  [ModuleType.RHModel]: {
    title: "RH Model",
    category: "사망률 모델",
    role: "Renshaw-Haberman: Lee-Carter + cohort term.",
    input: "연령×연도 사망률.",
    output: "RH 적합 + 예측.",
    whenToUse: "Lee-Carter에 코호트 효과를 추가해 적합을 개선하고 싶을 때.",
    connections: "TransitionData → RHModel → MortalityResult.",
    commonErrors: "수렴이 까다로울 수 있습니다 — 데이터 기간/격자를 확인하세요.",
  },
  [ModuleType.PlatModel]: {
    title: "Plat Model",
    category: "사망률 모델",
    role: "Plat 모델: 연령·기간·코호트를 결합한 다요인 사망률 모델.",
    input: "연령×연도 사망률.",
    output: "Plat 적합 + 예측.",
    whenToUse: "전 연령대를 아우르는 유연한 사망률 모델이 필요할 때.",
    connections: "TransitionData → PlatModel → MortalityResult.",
    commonErrors: "모수가 많아 표본이 작으면 과적합/불안정.",
  },
  [ModuleType.PSplineModel]: {
    title: "P-Spline Model",
    category: "사망률 모델",
    role: "Penalized spline으로 사망률 곡면을 매끄럽게 적합.",
    input: "연령×연도 사망률.",
    output: "스무딩된 곡면 + 예측.",
    whenToUse: "구조적 가정 없이 사망률 표면을 부드럽게 적합·평활하고 싶을 때.",
    connections: "TransitionData → PSplineModel → MortalityResult.",
    commonErrors: "평활 모수가 크면 과평활, 작으면 과적합 — 균형을 확인하세요.",
  },

  // ===== Freq-Sev Simulation =====
  [ModuleType.SimulateFreqSevTable]: {
    title: "Simulate Freq-Sev Table",
    category: "손해 시뮬레이션",
    role: "빈도(Frequency) × 심도(Severity) 가정으로 손해 시뮬레이션 테이블 생성.",
    input: "빈도/심도 분포 파라미터.",
    output: "시뮬레이션된 손해 분포 테이블.",
    whenToUse: "보험 손해의 집계 분포를 몬테카를로로 추정할 때.",
    connections: "(파라미터 입력) → SimulateFreqSevTable → CombineLossModel.",
    commonErrors: "시뮬레이션 횟수가 적으면 꼬리(tail) 추정이 부정확합니다.",
  },
  [ModuleType.CombineLossModel]: {
    title: "Combine Loss Model",
    category: "손해 시뮬레이션",
    role: "여러 손해 모델을 결합해 종합 손해 분포를 산출.",
    input: "복수 손해 모델.",
    output: "통합 손해 분포 + VaR/TVaR.",
    whenToUse: "여러 담보/계층의 손해를 합산해 총 위험(VaR/TVaR)을 평가할 때.",
    connections: "SimulateFreqSevTable(들) → CombineLossModel.",
    commonErrors: "분포 간 의존(상관) 구조를 무시하면 꼬리 위험을 과소평가할 수 있습니다.",
  },

};
